Repository notwaldorf/tiny-care-terminal, pull requests merged in 2018-03, with the labels that each got.

#124 "Last 24 hours" instead of "Today"
  care.js
Labels: 🎉 feature request

#130 Use username specified in local git config
  gitbot.js
  package.json
Labels: 🚨 bug

#120 Escape shell args
  care.js
  package.json
  standup-helper.sh
Labels: ⏳ pending-response, 🚨 bug

#117 Default pomodoro variables
  README.md
  care.js
  config.js
  pomodoro.js
  sample.env
Labels: 🎉 feature request

#134 show loading message while loading commits
  care.js
Labels: 🎉 feature request

#138 removed support for git-standup
  README.md
  care.js
  config.js
  package.json
  sample.env
  standup-helper.sh
Labels: 🚨 bug
